name: Test Docker S3 and DynamoDB

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_SECRET_ACCESS_KEY: fake
  AWS_ACCESS_KEY_ID: fake

defaults:
  run:
    shell: bash

on: push

jobs:
  Build_Test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build DockerS3DynamoDBTest.sln
      - name: Start docker
        run: docker-compose up -d
      - name: Check containers
        run: |
          docker ps
          aws --version
          aws dynamodb list-tables --endpoint-url http://localhost:8000
          curl -f -v http://127.0.0.1:9000/minio/health/live
      - name: run test
        run: dotnet test -ds:true
      - name: Stop docker
        run: docker-compose down
